name: 01 - First Workflow
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 <> Echo a string
        run: echo "Merhaba Dünya"
      - name: Step 2 <> Multiline Command
        run: |
          node -v
          npm -v
