name: 03 - Skipping Workflow Run
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 <> Echo a string
        run: echo "Merhaba Dünya"
      - name: Step 2 <> Multiline Command
        run: |
          node -v
          npm -v


# Workflows that would otherwise be triggered using on: push or on: pull_request won't be triggered if you add any of the following strings to the commit message in a push, or the HEAD commit of a pull request:

# [skip ci]
# [ci skip]
# [no ci]
# [skip actions]
# [actions skip]

# Alternatively, you can add a skip-checks trailer to your commit message. The trailers section should be included at the end of your commit message and be proceeded by two empty lines. If you already have other trailers in your commit message, skip-checks should be last. You can use either of the following:

# skip-checks:true
# skip-checks: true
